In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../datasets/recruitment_data.csv")

In [6]:
df.shape

(1000, 25)

In [7]:
df.head()

,candidate_id,candidate_name,job_id,job_title,department,source,recruiter,job_posted_date,application_date,screening_date,...,status,match_score,technical_score,communication_score,problem_solving_score,experience_years,education,offer_status,joining_status,recruitment_cost
0,C0001,Rahul Joshi,J002,Data Scientist,AI & ML,Naukri,Priya,2026-02-24,2026-03-04,2026-03-09,...,Selected,58,61,81,68,3.0,MBA,Not Applicable,Not Applicable,2520
1,C0002,Sneha Kulkarni,J001,Data Analyst,Data & Analytics,Career Website,Priya,2026-02-12,2026-03-01,2026-03-06,...,Screened,67,72,72,62,5.7,MCA,Not Applicable,Not Applicable,8873
2,C0003,Pooja Jadhav,J004,Python Developer,Software Development,LinkedIn,Rahul,2026-02-15,2026-03-13,2026-03-16,...,Shortlisted,40,49,87,40,2.4,MBA,Not Applicable,Not Applicable,5527
3,C0004,Sneha Patil,J006,ML Engineer,AI & ML,Indeed,Sneha,2026-04-04,2026-04-08,2026-04-09,...,Screened,61,46,95,58,1.1,MCA,Not Applicable,Not Applicable,13955
4,C0005,Ananya Patil,J008,Web Developer,IT,Career Website,Sneha,2026-04-04,2026-04-07,2026-04-10,...,Interviewed,99,100,79,93,1.6,MBA,Not Applicable,Not Applicable,13543

In [8]:
df.columns

Index(['candidate_id', 'candidate_name', 'job_id', 'job_title', 'department',
       'source', 'recruiter', 'job_posted_date', 'application_date',
       'screening_date', 'shortlist_date', 'interview_date', 'selection_date',
       'offer_date', 'joining_date', 'status', 'match_score',
       'technical_score', 'communication_score', 'problem_solving_score',
       'experience_years', 'education', 'offer_status', 'joining_status',
       'recruitment_cost'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   candidate_id           1000 non-null   str
 1   candidate_name         1000 non-null   str
 2   job_id                 1000 non-null   str
 3   job_title              1000 non-null   str
 4   department             1000 non-null   str
 5   source                 1000 non-null   str
 6   recruiter              1000 non-null   str
 7   job_posted_date        1000 non-null   str
 8   application_date       1000 non-null   str
 9   screening_date         807 non-null    str
 10  shortlist_date         657 non-null    str
 11  interview_date         495 non-null    str
 12  selection_date         330 non-null    str
 13  offer_date             189 non-null    str
 14  joining_date           102 non-null    str
 15  status                 1000 non-null   str
 16  match_score            1000 non-null   int64
 17  technical_score        1000 non-null   int64
 18  communication_score    1000 non-null   int64
 19  problem_solving_score  1000 non-null   int64
 20  experience_years       1000 non-null   float64
 21  education              1000 non-null   str
 22  offer_status           1000 non-null   str
 23  joining_status         1000 non-null   str
 24  recruitment_cost       1000 non-null   int64
dtypes: float64(1), int64(5), str(19)
memory usage: 195.4 KB

In [10]:
df.isnull().sum()

candidate_id               0
candidate_name             0
job_id                     0
job_title                  0
department                 0
source                     0
recruiter                  0
job_posted_date            0
application_date           0
screening_date           193
shortlist_date           343
interview_date           505
selection_date           670
offer_date               811
joining_date             898
status                     0
match_score                0
technical_score            0
communication_score        0
problem_solving_score      0
experience_years           0
education                  0
offer_status               0
joining_status             0
recruitment_cost           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.dtypes

candidate_id                 str
candidate_name               str
job_id                       str
job_title                    str
department                   str
source                       str
recruiter                    str
job_posted_date              str
application_date             str
screening_date               str
shortlist_date               str
interview_date               str
selection_date               str
offer_date                   str
joining_date                 str
status                       str
match_score                int64
technical_score            int64
communication_score        int64
problem_solving_score      int64
experience_years         float64
education                    str
offer_status                 str
joining_status               str
recruitment_cost           int64
dtype: object

In [13]:
date_columns = [
    "job_posted_date",
    "application_date",
    "screening_date",
    "shortlist_date",
    "interview_date",
    "selection_date",
    "offer_date",
    "joining_date"
]

for column in date_columns:
    df[column] = pd.to_datetime(df[column])

In [14]:
df.dtypes

candidate_id                        str
candidate_name                      str
job_id                              str
job_title                           str
department                          str
source                              str
recruiter                           str
job_posted_date          datetime64[us]
application_date         datetime64[us]
screening_date           datetime64[us]
shortlist_date           datetime64[us]
interview_date           datetime64[us]
selection_date           datetime64[us]
offer_date               datetime64[us]
joining_date             datetime64[us]
status                              str
match_score                       int64
technical_score                   int64
communication_score               int64
problem_solving_score             int64
experience_years                float64
education                           str
offer_status                        str
joining_status                      str
recruitment_cost                  int64
dtype: object

In [15]:
df[[
    "match_score",
    "technical_score",
    "communication_score",
    "problem_solving_score"
]].describe()

,match_score,technical_score,communication_score,problem_solving_score
count,1000.000000,1000.000000,1000.00000,1000.000000
mean,73.648000,73.265000,77.75000,73.039000
std,14.479356,16.781728,11.35105,16.252804
min,40.000000,40.000000,41.00000,40.000000
25%,64.000000,62.000000,70.00000,62.000000
50%,74.500000,73.000000,78.00000,74.000000
75%,84.000000,86.000000,86.00000,85.250000
max,99.000000,100.000000,100.00000,100.000000

In [16]:
df[[
    "experience_years",
    "recruitment_cost"
]].describe()

       experience_years  recruitment_cost
count       1000.000000       1000.000000
mean           3.904800       8667.100000
std            2.313008       3723.162438
min            0.000000       2034.000000
25%            1.900000       5516.750000
50%            3.800000       8563.000000
75%            5.900000      12009.000000
max            8.000000      14994.000000

In [17]:
df["status"].value_counts()

status
Applied        193
Interviewed    165
Shortlisted    162
Screened       150
Selected       141
Joined         102
Offered         87
Name: count, dtype: int64

In [18]:
df["source"].value_counts()

source
Naukri            194
Campus Hiring     186
Career Website    162
Indeed            160
LinkedIn          151
Referral          147
Name: count, dtype: int64

In [19]:
df["department"].value_counts()

department
Software Development    343
AI & ML                 270
Business                133
IT                      128
Data & Analytics        126
Name: count, dtype: int64

In [20]:
df["status"].value_counts()

status
Applied        193
Interviewed    165
Shortlisted    162
Screened       150
Selected       141
Joined         102
Offered         87
Name: count, dtype: int64

In [21]:
df["source"].value_counts()

source
Naukri            194
Campus Hiring     186
Career Website    162
Indeed            160
LinkedIn          151
Referral          147
Name: count, dtype: int64

In [22]:
df["department"].value_counts()

department
Software Development    343
AI & ML                 270
Business                133
IT                      128
Data & Analytics        126
Name: count, dtype: int64

In [23]:
df[df["status"] == "Joined"][[
    "status",
    "selection_date",
    "offer_date",
    "joining_date"
]].isnull().sum()

status            0
selection_date    0
offer_date        0
joining_date      0
dtype: int64

In [24]:
df[df["status"] == "Applied"][[
    "screening_date",
    "shortlist_date",
    "interview_date",
    "selection_date",
    "offer_date",
    "joining_date"
]].notnull().sum()

screening_date    0
shortlist_date    0
interview_date    0
selection_date    0
offer_date        0
joining_date      0
dtype: int64

In [25]:
df["time_to_hire"] = (
    df["joining_date"] - df["application_date"]
).dt.days

In [26]:
df[["status", "application_date", "joining_date", "time_to_hire"]].head(10)

        status application_date joining_date  time_to_hire
0     Selected       2026-03-04          NaT           NaN
1     Screened       2026-03-01          NaT           NaN
2  Shortlisted       2026-03-13          NaT           NaN
3     Screened       2026-04-08          NaT           NaN
4  Interviewed       2026-04-07          NaT           NaN
5  Shortlisted       2026-07-17          NaT           NaN
6  Interviewed       2026-06-21          NaT           NaN
7      Offered       2026-02-26          NaT           NaN
8     Screened       2026-04-12          NaT           NaN
9     Screened       2026-04-20          NaT           NaN

In [27]:
df[[
    "job_posted_date",
    "joining_date",
    "time_to_fill"
]].head(10)

KeyError: "['time_to_fill'] not in index"

In [28]:
df["time_to_fill"] = (
    df["joining_date"] - df["job_posted_date"]
).dt.days

In [29]:
df[[
    "job_posted_date",
    "joining_date",
    "time_to_fill"
]].head(10)

  job_posted_date joining_date  time_to_fill
0      2026-02-24          NaT           NaN
1      2026-02-12          NaT           NaN
2      2026-02-15          NaT           NaN
3      2026-04-04          NaT           NaN
4      2026-04-04          NaT           NaN
5      2026-07-07          NaT           NaN
6      2026-06-12          NaT           NaN
7      2026-02-04          NaT           NaN
8      2026-03-14          NaT           NaN
9      2026-03-22          NaT           NaN

In [30]:
df["overall_interview_score"] = (
    df["technical_score"]
    + df["communication_score"]
    + df["problem_solving_score"]
) / 3

df["overall_interview_score"] = df[
    "overall_interview_score"
].round(2)

In [31]:
df[[
    "technical_score",
    "communication_score",
    "problem_solving_score",
    "overall_interview_score"
]].head(10)

,technical_score,communication_score,problem_solving_score,overall_interview_score
0,61,81,68,70.00
1,72,72,62,68.67
2,49,87,40,58.67
3,46,95,58,66.33
4,100,79,93,90.67
5,62,70,83,71.67
6,65,75,69,69.67
7,58,62,79,66.33
8,86,65,62,71.00
9,78,82,50,70.00

In [32]:
df[[
    "time_to_hire",
    "time_to_fill",
    "overall_interview_score"
]].describe()

       time_to_hire  time_to_fill  overall_interview_score
count    102.000000    102.000000              1000.000000
mean      29.205882     45.970588                74.684720
std        5.611760     10.303759                10.845092
min       16.000000     25.000000                48.330000
25%       25.000000     38.250000                67.000000
50%       29.500000     46.500000                75.000000
75%       33.000000     54.000000                83.000000
max       44.000000     67.000000                99.000000

In [33]:
funnel = {
    "Applied": df["application_date"].notna().sum(),
    "Screened": df["screening_date"].notna().sum(),
    "Shortlisted": df["shortlist_date"].notna().sum(),
    "Interviewed": df["interview_date"].notna().sum(),
    "Selected": df["selection_date"].notna().sum(),
    "Offered": df["offer_date"].notna().sum(),
    "Joined": df["joining_date"].notna().sum()
}

funnel

{'Applied': np.int64(1000),
 'Screened': np.int64(807),
 'Shortlisted': np.int64(657),
 'Interviewed': np.int64(495),
 'Selected': np.int64(330),
 'Offered': np.int64(189),
 'Joined': np.int64(102)}

In [34]:
funnel_df = pd.DataFrame(
    list(funnel.items()),
    columns=["Stage", "Candidates"]
)

funnel_df

         Stage  Candidates
0      Applied        1000
1     Screened         807
2  Shortlisted         657
3  Interviewed         495
4     Selected         330
5      Offered         189
6       Joined         102

In [35]:
funnel_df["Conversion_Rate"] = (
    funnel_df["Candidates"] /
    funnel_df["Candidates"].shift(1)
) * 100

In [36]:
funnel_df

         Stage  Candidates  Conversion_Rate
0      Applied        1000              NaN
1     Screened         807        80.700000
2  Shortlisted         657        81.412639
3  Interviewed         495        75.342466
4     Selected         330        66.666667
5      Offered         189        57.272727
6       Joined         102        53.968254

In [37]:
overall_hiring_rate = (
    funnel["Joined"] / funnel["Applied"]
) * 100

overall_hiring_rate

np.float64(10.2)

In [38]:
round(overall_hiring_rate, 2)

np.float64(10.2)

In [39]:
funnel_df.to_csv(
    "../datasets/recruitment_funnel.csv",
    index=False
)

In [40]:
total_applicants = df["application_date"].notna().sum()
total_joined = df["joining_date"].notna().sum()

print("Total Applicants:", total_applicants)
print("Total Joined:", total_joined)

Total Applicants: 1000
Total Joined: 102

In [41]:
avg_time_to_hire = df["time_to_hire"].mean()

print("Average Time to Hire:", round(avg_time_to_hire, 2), "days")

Average Time to Hire: 29.21 days

In [42]:
avg_time_to_fill = df["time_to_fill"].mean()

print("Average Time to Fill:", round(avg_time_to_fill, 2), "days")

Average Time to Fill: 45.97 days

In [43]:
avg_interview_score = df["overall_interview_score"].mean()

print(
    "Average Interview Score:",
    round(avg_interview_score, 2)
)

Average Interview Score: 74.68

In [44]:
df["offer_status"].value_counts()

offer_status
Not Applicable    811
Accepted          170
Rejected           19
Name: count, dtype: int64

In [45]:
accepted_offers = (df["offer_status"] == "Accepted").sum()
rejected_offers = (df["offer_status"] == "Rejected").sum()

offer_acceptance_rate = (
    accepted_offers /
    (accepted_offers + rejected_offers)
) * 100

print("Offer Acceptance Rate:", round(offer_acceptance_rate, 2), "%")

Offer Acceptance Rate: 89.95 %

In [46]:
total_selected = df["selection_date"].notna().sum()

hiring_success_rate = (
    total_joined / total_selected
) * 100

print("Total Selected:", total_selected)
print("Hiring Success Rate:", round(hiring_success_rate, 2), "%")

Total Selected: 330
Hiring Success Rate: 30.91 %

In [47]:
kpi_df = pd.DataFrame({
    "KPI": [
        "Total Applicants",
        "Total Joined",
        "Average Time to Hire",
        "Average Time to Fill",
        "Average Interview Score",
        "Offer Acceptance Rate",
        "Hiring Success Rate"
    ],
    "Value": [
        total_applicants,
        total_joined,
        round(avg_time_to_hire, 2),
        round(avg_time_to_fill, 2),
        round(avg_interview_score, 2),
        round(offer_acceptance_rate, 2),
        round(hiring_success_rate, 2)
    ]
})

kpi_df

                       KPI    Value
0         Total Applicants  1000.00
1             Total Joined   102.00
2     Average Time to Hire    29.21
3     Average Time to Fill    45.97
4  Average Interview Score    74.68
5    Offer Acceptance Rate    89.95
6      Hiring Success Rate    30.91

In [48]:
kpi_df.to_csv(
    "../datasets/recruitment_kpis.csv",
    index=False
)

In [49]:
source_applicants = (
    df.groupby("source")["candidate_id"]
    .count()
    .sort_values(ascending=False)
)

source_applicants

source
Naukri            194
Campus Hiring     186
Career Website    162
Indeed            160
LinkedIn          151
Referral          147
Name: candidate_id, dtype: int64

In [50]:
source_joined = (
    df[df["joining_date"].notna()]
    .groupby("source")["candidate_id"]
    .count()
    .sort_values(ascending=False)
)

source_joined

source
Career Website    21
Campus Hiring     19
Indeed            19
LinkedIn          17
Naukri            16
Referral          10
Name: candidate_id, dtype: int64

In [51]:
source_analytics = pd.DataFrame({
    "Applicants": source_applicants,
    "Joined": source_joined
}).fillna(0)

source_analytics["Hiring_Rate"] = (
    source_analytics["Joined"] /
    source_analytics["Applicants"]
) * 100

source_analytics["Hiring_Rate"] = (
    source_analytics["Hiring_Rate"].round(2)
)

source_analytics

                Applicants  Joined  Hiring_Rate
source
Campus Hiring          186      19        10.22
Career Website         162      21        12.96
Indeed                 160      19        11.88
LinkedIn               151      17        11.26
Naukri                 194      16         8.25
Referral               147      10         6.80

In [52]:
best_source = source_analytics["Hiring_Rate"].idxmax()
best_rate = source_analytics["Hiring_Rate"].max()

print("Best Recruitment Source:", best_source)
print("Hiring Rate:", best_rate, "%")

Best Recruitment Source: Career Website
Hiring Rate: 12.96 %

In [53]:
source_score = (
    df.groupby("source")["overall_interview_score"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

source_score

source
Career Website    76.15
Referral          75.67
Naukri            74.39
Campus Hiring     74.13
LinkedIn          74.07
Indeed            73.87
Name: overall_interview_score, dtype: float64

In [54]:
source_analytics["Avg_Interview_Score"] = source_score

source_analytics = source_analytics.sort_values(
    "Hiring_Rate",
    ascending=False
)

source_analytics

                Applicants  Joined  Hiring_Rate  Avg_Interview_Score
source
Career Website         162      21        12.96                76.15
Indeed                 160      19        11.88                73.87
LinkedIn               151      17        11.26                74.07
Campus Hiring          186      19        10.22                74.13
Naukri                 194      16         8.25                74.39
Referral               147      10         6.80                75.67

In [55]:
source_analytics.to_csv(
    "../datasets/source_analytics.csv"
)

In [56]:
department_applicants = (
    df.groupby("department")["candidate_id"]
    .count()
    .sort_values(ascending=False)
)

department_applicants

department
Software Development    343
AI & ML                 270
Business                133
IT                      128
Data & Analytics        126
Name: candidate_id, dtype: int64

In [57]:
department_joined = (
    df[df["joining_date"].notna()]
    .groupby("department")["candidate_id"]
    .count()
    .sort_values(ascending=False)
)

department_joined

department
Software Development    34
AI & ML                 31
IT                      15
Business                14
Data & Analytics         8
Name: candidate_id, dtype: int64

In [58]:
department_analytics = pd.DataFrame({
    "Applicants": department_applicants,
    "Joined": department_joined
}).fillna(0)

department_analytics["Hiring_Rate"] = (
    department_analytics["Joined"] /
    department_analytics["Applicants"]
) * 100

department_analytics["Hiring_Rate"] = (
    department_analytics["Hiring_Rate"].round(2)
)

department_analytics

                      Applicants  Joined  Hiring_Rate
department
AI & ML                      270      31        11.48
Business                     133      14        10.53
Data & Analytics             126       8         6.35
IT                           128      15        11.72
Software Development         343      34         9.91

In [59]:
department_score = (
    df.groupby("department")["overall_interview_score"]
    .mean()
    .round(2)
)

department_score

department
AI & ML                 74.48
Business                74.38
Data & Analytics        75.60
IT                      76.25
Software Development    74.05
Name: overall_interview_score, dtype: float64

In [60]:
department_analytics["Avg_Interview_Score"] = department_score

department_analytics = department_analytics.sort_values(
    "Hiring_Rate",
    ascending=False
)

department_analytics

                      Applicants  Joined  Hiring_Rate  Avg_Interview_Score
department
IT                           128      15        11.72                76.25
AI & ML                      270      31        11.48                74.48
Business                     133      14        10.53                74.38
Software Development         343      34         9.91                74.05
Data & Analytics             126       8         6.35                75.60

In [61]:
department_analytics.to_csv(
    "../datasets/department_analytics.csv"
)

In [62]:
df["recruiter_name"].value_counts()

KeyError: 'recruiter_name'

In [63]:
[col for col in df.columns if "recruit" in col.lower()]

['recruiter', 'recruitment_cost']

In [64]:
recruiter_applicants = (
    df.groupby("recruiter")["candidate_id"]
    .count()
    .sort_values(ascending=False)
)

recruiter_applicants

recruiter
Sneha    219
Amit     203
Rahul    202
Priya    195
Neha     181
Name: candidate_id, dtype: int64

In [65]:
recruiter_shortlisted = (
    df[df["shortlist_date"].notna()]
    .groupby("recruiter")["candidate_id"]
    .count()
)

recruiter_shortlisted

recruiter
Amit     131
Neha     121
Priya    132
Rahul    125
Sneha    148
Name: candidate_id, dtype: int64

In [66]:
recruiter_interviewed = (
    df[df["interview_date"].notna()]
    .groupby("recruiter")["candidate_id"]
    .count()
)

recruiter_interviewed

recruiter
Amit     100
Neha      90
Priya    100
Rahul     95
Sneha    110
Name: candidate_id, dtype: int64

In [67]:
recruiter_offers = (
    df[df["offer_date"].notna()]
    .groupby("recruiter")["candidate_id"]
    .count()
)

recruiter_offers

recruiter
Amit     34
Neha     34
Priya    44
Rahul    35
Sneha    42
Name: candidate_id, dtype: int64

In [68]:
recruiter_joined = (
    df[df["joining_date"].notna()]
    .groupby("recruiter")["candidate_id"]
    .count()
)

recruiter_joined

recruiter
Amit     19
Neha     17
Priya    27
Rahul    18
Sneha    21
Name: candidate_id, dtype: int64

In [69]:
recruiter_analytics = pd.DataFrame({
    "Candidates_Sourced": recruiter_applicants,
    "Shortlisted": recruiter_shortlisted,
    "Interviewed": recruiter_interviewed,
    "Offers": recruiter_offers,
    "Joined": recruiter_joined
}).fillna(0)

recruiter_analytics

           Candidates_Sourced  Shortlisted  Interviewed  Offers  Joined
recruiter
Amit                      203          131          100      34      19
Neha                      181          121           90      34      17
Priya                     195          132          100      44      27
Rahul                     202          125           95      35      18
Sneha                     219          148          110      42      21

In [70]:
recruiter_analytics["Hiring_Rate"] = (
    recruiter_analytics["Joined"] /
    recruiter_analytics["Candidates_Sourced"]
) * 100

recruiter_analytics["Hiring_Rate"] = (
    recruiter_analytics["Hiring_Rate"].round(2)
)

recruiter_analytics = recruiter_analytics.sort_values(
    "Hiring_Rate",
    ascending=False
)

recruiter_analytics

,Candidates_Sourced,Shortlisted,Interviewed,Offers,Joined,Hiring_Rate
recruiter,,,,,,
Priya,195,132,100,44,27,13.85
Sneha,219,148,110,42,21,9.59
Neha,181,121,90,34,17,9.39
Amit,203,131,100,34,19,9.36
Rahul,202,125,95,35,18,8.91

In [71]:
recruiter_analytics.to_csv(
    "../datasets/recruiter_analytics.csv"
)

In [72]:
df["joining_month"] = df["joining_date"].dt.to_period("M").astype(str)

In [73]:
monthly_hiring = (
    df[df["joining_date"].notna()]
    .groupby("joining_month")["candidate_id"]
    .count()
    .reset_index(name="Hires")
)

monthly_hiring

  joining_month  Hires
0       2026-02     17
1       2026-03      8
2       2026-04     19
3       2026-05     13
4       2026-06     11
5       2026-07     15
6       2026-08     12
7       2026-09      7

In [74]:
monthly_hiring.to_csv(
    "../datasets/monthly_hiring.csv",
    index=False
)

In [75]:
df["skills"].head(10)

KeyError: 'skills'

In [76]:
[col for col in df.columns if "skill" in col.lower()]

[]

In [77]:
df.columns.tolist()

['candidate_id',
 'candidate_name',
 'job_id',
 'job_title',
 'department',
 'source',
 'recruiter',
 'job_posted_date',
 'application_date',
 'screening_date',
 'shortlist_date',
 'interview_date',
 'selection_date',
 'offer_date',
 'joining_date',
 'status',
 'match_score',
 'technical_score',
 'communication_score',
 'problem_solving_score',
 'experience_years',
 'education',
 'offer_status',
 'joining_status',
 'recruitment_cost',
 'time_to_hire',
 'time_to_fill',
 'overall_interview_score',
 'joining_month']

In [78]:
total_recruitment_cost = df["recruitment_cost"].sum()

print(
    "Total Recruitment Cost: ₹",
    round(total_recruitment_cost, 2)
)

Total Recruitment Cost: ₹ 8667100

In [79]:
avg_recruitment_cost = df["recruitment_cost"].mean()

print(
    "Average Recruitment Cost per Candidate: ₹",
    round(avg_recruitment_cost, 2)
)

Average Recruitment Cost per Candidate: ₹ 8667.1

In [80]:
cost_per_hire = (
    total_recruitment_cost / total_joined
)

print(
    "Cost per Hire: ₹",
    round(cost_per_hire, 2)
)

Cost per Hire: ₹ 84971.57

In [81]:
source_cost = (
    df.groupby("source")["recruitment_cost"]
    .sum()
    .sort_values(ascending=False)
)

source_cost

source
Naukri            1653078
Campus Hiring     1601829
Career Website    1421573
Indeed            1345377
Referral          1336217
LinkedIn          1309026
Name: recruitment_cost, dtype: int64

In [82]:
source_cost_analytics = source_analytics.copy()

source_cost_analytics["Total_Cost"] = source_cost

source_cost_analytics["Cost_Per_Hire"] = (
    source_cost_analytics["Total_Cost"] /
    source_cost_analytics["Joined"]
).round(2)

source_cost_analytics

,Applicants,Joined,Hiring_Rate,Avg_Interview_Score,Total_Cost,Cost_Per_Hire
source,,,,,,
Career Website,162,21,12.96,76.15,1421573,67693.95
Indeed,160,19,11.88,73.87,1345377,70809.32
LinkedIn,151,17,11.26,74.07,1309026,77001.53
Campus Hiring,186,19,10.22,74.13,1601829,84306.79
Naukri,194,16,8.25,74.39,1653078,103317.38
Referral,147,10,6.80,75.67,1336217,133621.70

In [83]:
source_cost_analytics.sort_values(
    "Cost_Per_Hire"
)

,Applicants,Joined,Hiring_Rate,Avg_Interview_Score,Total_Cost,Cost_Per_Hire
source,,,,,,
Career Website,162,21,12.96,76.15,1421573,67693.95
Indeed,160,19,11.88,73.87,1345377,70809.32
LinkedIn,151,17,11.26,74.07,1309026,77001.53
Campus Hiring,186,19,10.22,74.13,1601829,84306.79
Naukri,194,16,8.25,74.39,1653078,103317.38
Referral,147,10,6.80,75.67,1336217,133621.70

In [84]:
source_cost_analytics.to_csv(
    "../datasets/source_cost_analytics.csv"
)

In [85]:
department_cost = (
    df.groupby("department")["recruitment_cost"]
    .sum()
    .sort_values(ascending=False)
)

department_cost

department
Software Development    3025710
AI & ML                 2285842
Data & Analytics        1141281
Business                1113980
IT                      1100287
Name: recruitment_cost, dtype: int64

In [86]:
department_cost_analytics = department_analytics.copy()

department_cost_analytics["Total_Cost"] = department_cost

department_cost_analytics["Cost_Per_Hire"] = (
    department_cost_analytics["Total_Cost"] /
    department_cost_analytics["Joined"]
).round(2)

department_cost_analytics

,Applicants,Joined,Hiring_Rate,Avg_Interview_Score,Total_Cost,Cost_Per_Hire
department,,,,,,
IT,128,15,11.72,76.25,1100287,73352.47
AI & ML,270,31,11.48,74.48,2285842,73736.84
Business,133,14,10.53,74.38,1113980,79570.00
Software Development,343,34,9.91,74.05,3025710,88991.47
Data & Analytics,126,8,6.35,75.60,1141281,142660.12

In [87]:
department_cost_analytics.sort_values(
    "Cost_Per_Hire"
)

,Applicants,Joined,Hiring_Rate,Avg_Interview_Score,Total_Cost,Cost_Per_Hire
department,,,,,,
IT,128,15,11.72,76.25,1100287,73352.47
AI & ML,270,31,11.48,74.48,2285842,73736.84
Business,133,14,10.53,74.38,1113980,79570.00
Software Development,343,34,9.91,74.05,3025710,88991.47
Data & Analytics,126,8,6.35,75.60,1141281,142660.12

In [88]:
department_cost_analytics.to_csv(
    "../datasets/department_cost_analytics.csv"
)

In [89]:
df["match_category"] = pd.cut(
    df["match_score"],
    bins=[0, 59, 74, 89, 100],
    labels=["Low", "Average", "Good", "Excellent"]
)

In [90]:
match_distribution = (
    df["match_category"]
    .value_counts()
    .sort_index()
)

match_distribution

match_category
Low          164
Average      336
Good         350
Excellent    150
Name: count, dtype: int64

In [91]:
match_effectiveness = (
    df.groupby("match_category", observed=True)
    .agg(
        Applicants=("candidate_id", "count"),
        Joined=("joining_date", lambda x: x.notna().sum())
    )
)

match_effectiveness["Hiring_Rate"] = (
    match_effectiveness["Joined"] /
    match_effectiveness["Applicants"]
) * 100

match_effectiveness["Hiring_Rate"] = (
    match_effectiveness["Hiring_Rate"].round(2)
)

match_effectiveness

                Applicants  Joined  Hiring_Rate
match_category
Low                    164      12         7.32
Average                336      39        11.61
Good                   350      37        10.57
Excellent              150      14         9.33

In [92]:
match_effectiveness.to_csv(
    "../datasets/match_effectiveness.csv"
)

In [93]:
df["experience_category"] = pd.cut(
    df["experience_years"],
    bins=[-1, 1, 3, 5, 10, float("inf")],
    labels=[
        "0-1 Years",
        "2-3 Years",
        "4-5 Years",
        "6-10 Years",
        "10+ Years"
    ]
)

In [94]:
experience_effectiveness = (
    df.groupby("experience_category", observed=True)
    .agg(
        Applicants=("candidate_id", "count"),
        Joined=("joining_date", lambda x: x.notna().sum())
    )
)

experience_effectiveness["Hiring_Rate"] = (
    experience_effectiveness["Joined"] /
    experience_effectiveness["Applicants"]
) * 100

experience_effectiveness["Hiring_Rate"] = (
    experience_effectiveness["Hiring_Rate"].round(2)
)

experience_effectiveness

                     Applicants  Joined  Hiring_Rate
experience_category
0-1 Years                   135      15        11.11
2-3 Years                   268      27        10.07
4-5 Years                   239      28        11.72
6-10 Years                  358      32         8.94

In [95]:
experience_effectiveness.to_csv(
    "../datasets/experience_effectiveness.csv"
)

In [96]:
df["education"].value_counts()

education
B.E.      183
MBA       181
MCA       162
B.Sc      162
M.Tech    161
B.Tech    151
Name: count, dtype: int64

In [97]:
education_analytics = (
    df.groupby("education")
    .agg(
        Applicants=("candidate_id", "count"),
        Joined=("joining_date", lambda x: x.notna().sum())
    )
)

education_analytics

           Applicants  Joined
education
B.E.              183      13
B.Sc              162      21
B.Tech            151      15
M.Tech            161      21
MBA               181      20
MCA               162      12

In [98]:
education_analytics["Hiring_Rate"] = (
    education_analytics["Joined"] /
    education_analytics["Applicants"]
) * 100

education_analytics["Hiring_Rate"] = (
    education_analytics["Hiring_Rate"].round(2)
)

education_analytics

           Applicants  Joined  Hiring_Rate
education
B.E.              183      13         7.10
B.Sc              162      21        12.96
B.Tech            151      15         9.93
M.Tech            161      21        13.04
MBA               181      20        11.05
MCA               162      12         7.41

In [99]:
education_score = (
    df.groupby("education")["overall_interview_score"]
    .mean()
    .round(2)
)

education_analytics["Avg_Interview_Score"] = education_score

education_analytics

           Applicants  Joined  Hiring_Rate  Avg_Interview_Score
education
B.E.              183      13         7.10                74.93
B.Sc              162      21        12.96                73.78
B.Tech            151      15         9.93                73.90
M.Tech            161      21        13.04                74.98
MBA               181      20        11.05                74.96
MCA               162      12         7.41                75.45

In [100]:
education_analytics = education_analytics.sort_values(
    "Hiring_Rate",
    ascending=False
)

education_analytics

           Applicants  Joined  Hiring_Rate  Avg_Interview_Score
education
M.Tech            161      21        13.04                74.98
B.Sc              162      21        12.96                73.78
MBA               181      20        11.05                74.96
B.Tech            151      15         9.93                73.90
MCA               162      12         7.41                75.45
B.E.              183      13         7.10                74.93

In [101]:
education_analytics.to_csv(
    "../datasets/education_analytics.csv"
)